/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.formLogin;

/**
 *
 * @author FARHAN
 */
public class Dashboard extends javax.swing.JFrame {
    
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    public Connection kon = login.koneksi.KoneksiDb();
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        JDateChooser dateChooser = new JDateChooser();
        dateChooser.setDate(new Date());
        judul();
        tampilData("");
        PNAdmin.setEnabled(false);
        buttonHapus.setEnabled(false);
        buttonUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNAdmin = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablepasien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        notelepon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jk = new javax.swing.JComboBox<>();
        vaksin = new javax.swing.JComboBox<>();
        buttonSimpan = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        BTNUser = new javax.swing.JButton();
        BTNUser1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablepasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tablepasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablepasien);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("ID");

        id.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Nama");

        nama.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal Lahir");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setText("Alamat");

        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        alamat.setRows(5);
        jScrollPane2.setViewportView(alamat);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setText("No Telepon");

        notelepon.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setText("Info Vaksin");

        jk.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan", "Lainnya" }));

        vaksin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        vaksin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sudah Vaksin", "Belum Vaksin" }));

        buttonSimpan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonHapus.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonHapus.setText("Hapus");
        buttonHapus.setPreferredSize(new java.awt.Dimension(81, 23));
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonReset.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonReset.setText("Reset");
        buttonReset.setPreferredSize(new java.awt.Dimension(81, 23));
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        buttonUpdate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNAdminLayout = new javax.swing.GroupLayout(PNAdmin);
        PNAdmin.setLayout(PNAdminLayout);
        PNAdminLayout.setHorizontalGroup(
            PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PNAdminLayout.createSequentialGroup()
                        .addGroup(PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(buttonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(buttonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PNAdminLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vaksin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PNAdminLayout.createSequentialGroup()
                        .addGroup(PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id)
                            .addComponent(nama)
                            .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2)
                    .addGroup(PNAdminLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
        );
        PNAdminLayout.setVerticalGroup(
            PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNAdminLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(id)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nama)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(notelepon)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaksin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        BTNUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BTNUser.setText("User");
        BTNUser.setBorder(null);
        BTNUser.setBorderPainted(false);
        BTNUser.setContentAreaFilled(false);
        BTNUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUserActionPerformed(evt);
            }
        });

        BTNUser1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BTNUser1.setText("Log out");
        BTNUser1.setBorder(null);
        BTNUser1.setBorderPainted(false);
        BTNUser1.setContentAreaFilled(false);
        BTNUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(BTNUser, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNUser, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(BTNUser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PNAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
    try {
    st = kon.createStatement();

    // Mengubah format Date menjadi String dengan format 'yyyy-MM-dd'
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String tanggalFormatted = dateFormat.format(dateChooser.getDate());

    st.executeUpdate("UPDATE pasien SET"
            + " nama = '" + nama.getText() + "'"
            + ", tanggal_lahir = '" + tanggalFormatted + "'" // Menggunakan tanggal yang telah diformat
            + ", jenis_kelamin = '" + jk.getSelectedItem() + "'"
            + ", alamat = '" + alamat.getText() + "'"
            + ", no_telepon = '" + notelepon.getText() + "'"
            + ", sudah_vaksin = '" + vaksin.getSelectedItem() + "'"
            + " WHERE id = '" + id.getText() + "';");

    tampilData("");
    JOptionPane.showMessageDialog(null, "Update Berhasil");
    reset();
} catch (Exception e) {
    e.printStackTrace();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        reset();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        try {
            int confirmDialogResult;
            confirmDialogResult = JOptionPane.showConfirmDialog(null, "Konfirmasi Hapus Data ?", "KONFIRMASI", JOptionPane.YES_NO_OPTION);
            if (confirmDialogResult == JOptionPane.YES_OPTION) {
                st = kon.createStatement();
                st.executeUpdate("DELETE FROM pasien WHERE id='" + tabModel.getValueAt(tablepasien.getSelectedRow(), 0) + "'");
                tampilData("");
                reset();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        try {
        st = kon.createStatement();
        
        // Mengubah format Date menjadi String dengan format 'YYYY-MM-DD'
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalFormatted = dateFormat.format(dateChooser.getDate());

        st.executeUpdate("INSERT INTO pasien VALUES('" + id.getText() + "','"
                + nama.getText() + "','"
                + tanggalFormatted + "','" // Menggunakan tanggal yang telah diformat
                + jk.getSelectedItem() + "','"
                + alamat.getText() + "','"
                + notelepon.getText() + "','"
                + vaksin.getSelectedItem() + "')");

        tampilData("");
        JOptionPane.showMessageDialog(null, "Simpan Berhasil");
        reset();
    } catch (Exception e) {
        e.printStackTrace();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void tablepasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepasienMouseClicked
    // Mengatur nilai untuk JTextField id, nama, alamat, notelepon, dan JComboBox vaksin
    id.setText(tablepasien.getValueAt(tablepasien.getSelectedRow(), 0).toString());
    nama.setText(tablepasien.getValueAt(tablepasien.getSelectedRow(), 1).toString());
    alamat.setText(tablepasien.getValueAt(tablepasien.getSelectedRow(), 4).toString());
    notelepon.setText(tablepasien.getValueAt(tablepasien.getSelectedRow(), 5).toString());
    vaksin.setSelectedItem(tablepasien.getValueAt(tablepasien.getSelectedRow(), 6).toString());
    // Mengatur nilai untuk JComboBox jk
    jk.setSelectedItem(tablepasien.getValueAt(tablepasien.getSelectedRow(), 3).toString());
    buttonSimpan. setEnabled (false);
    buttonUpdate.setEnabled(true);
    buttonHapus.setEnabled (true);
    id.setEnabled(false);
    // Mengatur nilai untuk JDateChooser dateChooser
    try {
        String tanggalString = tablepasien.getValueAt(tablepasien.getSelectedRow(), 2).toString();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date tanggalDate = dateFormat.parse(tanggalString);
        dateChooser.setDate(tanggalDate);
    } catch (ParseException ex) {
        ex.printStackTrace();
    }

    }//GEN-LAST:event_tablepasienMouseClicked

    private void BTNUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUserActionPerformed
    DashboardUser2 fa = new DashboardUser2();
                fa.show();
                this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_BTNUserActionPerformed

    private void BTNLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLogOutActionPerformed
    formLogin fa = new formLogin();
                fa.show();
                this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNLogOutActionPerformed

    private void BTNUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUser1ActionPerformed
formLogin fa = new formLogin();
                fa.show();
                this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNUser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }
    public void judul() {
    Object[] judul = {"ID", "Nama", "Tanggal Lahir", "Jenis Kelamin", "Alamat", "No Telepon", "Info Vaksin"} ; 
    tabModel = new DefaultTableModel (null, judul); 
    tablepasien.setModel (tabModel);
    }
    public void tampilData(String where){
        try {
        st = kon.createStatement(); 
        tabModel.getDataVector().removeAllElements (); 
        tabModel.fireTableDataChanged (); 
        rs = st.executeQuery("SELECT * FROM pasien " + where);
            
        while (rs.next()){
        Object[] data = {
            rs.getString("id"),
            rs.getString("nama"),
            rs.getString("tanggal_lahir"), 
            rs.getString("jenis_kelamin"), 
            rs.getString("alamat"),
            rs.getString("no_telepon"),
            rs.getString("sudah_vaksin"),
        };
        
        tabModel.addRow(data);
        }
    } catch(Exception e) {
        e.printStackTrace();
    }
} 
    public void reset() {
        id.setText ("");
        nama.setText (""); 
        dateChooser.setDate(null);
        jk.setSelectedItem(""); 
        alamat.setText (""); 
        notelepon.setText("");
        vaksin.setSelectedItem("");
        buttonSimpan.setEnabled (true); 
        id.setEnabled (true); 
        buttonUpdate.setEnabled (false); 
        buttonHapus.setEnabled (false) ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNUser;
    private javax.swing.JButton BTNUser1;
    private javax.swing.JPanel PNAdmin;
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUpdate;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jk;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField notelepon;
    private javax.swing.JTable tablepasien;
    private javax.swing.JComboBox<String> vaksin;
    // End of variables declaration//GEN-END:variables
}
